package es.mgj.base;

// Generated 07-feb-2014 21:16:06 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;



/**
 * GameUser generated by hbm2java
 */

public class GameUser implements java.io.Serializable {

	private String id;
	private String nick;
	private String password;
	private Set<Character> characters = new HashSet<Character>(0);

	public GameUser() {
	}

	public GameUser(String id, String nick) {
		this.id = id;
		this.nick = nick;
	}

	public GameUser(String id, String nick, String password,
			Set<Character> characters) {
		this.id = id;
		this.nick = nick;
		this.password = password;
		this.characters = characters;
	}


	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}


	public String getNick() {
		return this.nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}


	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}


	public Set<Character> getCharacters() {
		return this.characters;
	}

	public void setCharacters(Set<Character> characters) {
		this.characters = characters;
	}

}
