package es.mgj.base;

// Generated 07-feb-2014 21:16:06 by Hibernate Tools 4.0.0

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;


/**
 * Object generated by hbm2java
 */

public class Object extends Tabla implements java.io.Serializable {

	private String id;
	private Character character;
	private String kind;
	private Float attack;
	private Float defence;
	private Float dropRate;

	public Object() {
	}

	public Object(String id) {
		this.id = id;
	}

	public Object(String id, Character character, String kind, Float attack,
			Float defence, Float dropRate) {
		this.id = id;
		this.character = character;
		this.kind = kind;
		this.attack = attack;
		this.defence = defence;
		this.dropRate = dropRate;
	}


	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}


	public Character getCharacter() {
		if(this.character == null){
			Character c = new Character();
			c.setName("Not dropped");
			return c;
		}
		return this.character;
	}

	public void setCharacter(Character character) {
		this.character = character;
	}


	public String getKind() {
		return this.kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}


	public Float getAttack() {
		return this.attack;
	}

	public void setAttack(Float attack) {
		this.attack = attack;
	}


	public Float getDefence() {
		return this.defence;
	}

	public void setDefence(Float defence) {
		this.defence = defence;
	}


	public Float getDropRate() {
		return this.dropRate;
	}

	public void setDropRate(Float dropRate) {
		this.dropRate = dropRate;
	}
	
	@Override
	public List<String> getCampos(){
		
		List<String> fields = new ArrayList<String>();
		
		for(Field nombre : Object.class.getDeclaredFields())
			fields.add(nombre.toString().substring(nombre.toString().lastIndexOf(".") + 1));
		
		return fields;
		
	}

	@Override
	public String toString(){
		return String.valueOf(this.id);
	}

}
