package es.mgj.base;

// Generated 07-feb-2014 21:16:06 by Hibernate Tools 4.0.0

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;


/**
 * Pet generated by hbm2java
 */

public class Pet extends Tabla implements java.io.Serializable {

	private String id;
	private Character character;
	private String name;
	private String ability;
	private String king;

	public Pet() {
	}

	public Pet(String id) {
		this.id = id;
	}

	public Pet(String id, Character character, String name, String ability,
			String king) {
		this.id = id;
		this.character = character;
		this.name = name;
		this.ability = ability;
		this.king = king;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}


	public Character getCharacter() {
		
		if(this.character == null){
			Character c = new Character();
			c.setName("free");
			return c;
		}
			
		return this.character;
	}

	public void setCharacter(Character character) {
		this.character = character;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAbility() {
		return this.ability;
	}

	public void setAbility(String ability) {
		this.ability = ability;
	}

	public String getKing() {
		return this.king;
	}

	public void setKing(String king) {
		this.king = king;
	}
	

	@Override
	public List<String> getCampos(){
		
		List<String> fields = new ArrayList<String>();
		
		for(Field nombre : Pet.class.getDeclaredFields())
			fields.add(nombre.toString().substring(nombre.toString().lastIndexOf(".") + 1));
		
		return fields;
		
	}
	

	@Override
	public String toString(){
		return this.name;
	}

}
